SET NAMES utf8;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    mail VARCHAR(40) NOT NULL,
    password VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
)
ENGINE=INNODB;